me: update web servers
  hosts: ubuntu
  become: yes

  tasks:
  - name: ensure web server is installed
    package:
      name: apache2
      state: present
    notify:
    - Remove Index
    - ensure site

  - name: ensure web server is started
    service:
      name: apache2
      state: started

  - name: ensure web server is enabled
    service:
      name: apache2
      enabled: yes

  handlers:
  - name: Remove Index
    file:
      path: /var/www/html/index.html
      state: absent

  - name: ensure site
    git:
      repo: https://github.com/ravi2krishna/ecomm.git
      dest: /var/www/html
...

