---
  - name: update app
    git:
      repo: https://github.com/ravi2krishna/ecomm.git
      dest: /var/www/html

  - name: Restart HTTPD
    service:
      name: httpd
      state: restarted

  - name: ensure web server is started
    service:
      name: httpd
      state: started

...

